name: "🚀 Feature request"
description: Suggest an idea for this project
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!

        Please carefully read the contribution docs before suggesting a new feature
        👉 https://github.com/thriving-dev/java-library-template/blob/main/CONTRIBUTING.md
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition, including the possible use cases and alternatives you have considered. If you have a working prototype that implements it, please include a link.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: Read the [contribution guide](https://github.com/thriving-dev/java-library-template/blob/main/CONTRIBUTING.md).
          required: true
        - label: Check existing [discussions](https://github.com/thriving-dev/java-library-template/discussions) and [issues](https://github.com/thriving-dev/java-library-template/issues).
          required: true
